# Generated by Django 2.0.5 on 2018-05-25 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_ID', models.CharField(default=None, max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='New Class', max_length=20, null=True)),
                ('dept_id', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('credits', models.DecimalField(decimal_places=1, max_digits=20)),
                ('course_capacity', models.IntegerField()),
                ('type', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('need_computer', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('period', models.IntegerField()),
                ('exam_method', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edu_manager',
            fields=[
                ('Mana_ID', models.CharField(default=None, max_length=20, primary_key=True, serialize=False)),
                ('Mana_name', models.CharField(blank=True, default='New User', max_length=20, null=True)),
                ('Mana_gender', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('Mana_password', models.CharField(blank=True, default='123456', max_length=20, null=True)),
                ('Mana_deptID', models.CharField(blank=True, default=None, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ins_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='infoSystem.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('ins_ID', models.CharField(default=None, max_length=20, primary_key=True, serialize=False)),
                ('ins_name', models.CharField(blank=True, default='New User', max_length=20, null=True)),
                ('ins_gender', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('ins_password', models.CharField(blank=True, default='123456', max_length=20, null=True)),
                ('dept_ID', models.CharField(blank=True, default=None, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_ID', models.CharField(default=None, max_length=20, primary_key=True, serialize=False)),
                ('stu_name', models.CharField(blank=True, default='New User', max_length=20, null=True)),
                ('stu_grade', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('stu_gender', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('major_ID', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('stu_password', models.CharField(blank=True, default='123456', max_length=20, null=True)),
                ('tot_cred', models.DecimalField(decimal_places=1, max_digits=20)),
                ('avatar', models.ImageField(default=None, null=True, upload_to='course/cover-img/')),
            ],
        ),
        migrations.CreateModel(
            name='Sys_manager',
            fields=[
                ('sys_ID', models.CharField(default=None, max_length=20, primary_key=True, serialize=False)),
                ('sys_name', models.CharField(blank=True, default='New User', max_length=20, null=True)),
                ('sys_gender', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('sys_password', models.CharField(blank=True, default='123456', max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ins_course',
            name='Ins_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='infoSystem.Instructor'),
        ),
    ]
